language: php

php:
  - 5.6

before_install:
  - mysql -e "create database IF NOT EXISTS calendar_bundle_test;" -uroot
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
 - composer install -n
 - ./reset-db.sh

services:
  - mysql

script:
  - ./bin/phpunit
